baseURL = "http://ericbaranowski.netlify.com/"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 5

[params]
  contentTypeName = "post"
  themeColor = "green"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    title = "Eric's Blog"
    subtitle = "Methods, Research, and Best Practices from the mind of Eric Baranowski"
    keywords = "Eric Baranowski"
    copyright = 'Copyright (c) 2019 Eric Baranowski. All rights reserved.'
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "/Users/ericbaranowski"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
